logging:
  level:
    org.springframework.security: trace

spring:
  security:
    oauth2:
      client:
        registration:
          my-client:
            provider: my-provider
            client-id: admin-client
            client-secret: secret
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_basic
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: read,openid
        provider:
          my-provider:
            issuer-uri: http://localhost:9000