logging:
  level:
    org.springframework.security: trace

spring:
  security:
    oauth2:
      authorizationserver:
        client:
          client-01:
            registration:
              client-id: admin-client
              # the client secret is "secret" (without quotes)
              client-secret: "{bcrypt}$2a$10$jdJGhzsiIqYFpjJiYWMl/eKDOd8vdyQis2aynmFN0dgJ53XvpzzwC"
              client-authentication-methods: client_secret_basic
              authorization-grant-types: client_credentials,authorization_code,refresh_token
              redirect-uris: http://127.0.0.1:8080/login/oauth2/code/my-client
              scopes: read,openid
            require-authorization-consent: true
server:
  port: 9000